services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"

  api:
    build:
      context: ./API
      dockerfile: Dockerfile-development
    volumes:
      - "./API:/src/app"
      - "/src/app/node_modules"
    environment:
      VIRTUAL_HOST: 'api.groupapp.io'
      NODE_ENV: 'development'
      MONGO_URL: mongodb://db:27017/groupapp
      PORT: 80

  chat:
    build:
      context: ./GroupChatStream
      dockerfile: Dockerfile-development
    volumes:
      - "./GroupChatStream:/src/app"
      - "/src/app/node_modules"
    environment:
      VIRTUAL_HOST: 'chat.groupapp.io'
      NODE_ENV: 'development'
      MONGO_URL: mongodb://db:27017/groupapp
      PORT: 80

  groupmaker:
    build:
      context: ./GroupMaker
      dockerfile: Dockerfile-development
    volumes:
      - "./GroupMaker:/src/app"
      - "/src/app/node_modules"
    environment:
      NODE_ENV: 'development'
      MONGO_URL: mongodb://db:27017/groupapp
      PORT: 80

  client:
    build:
      context: ./ClientDistro
      dockerfile: Dockerfile-development
    volumes:
      - "./ClientDistro:/src/app"
      - "/src/app/node_modules"
    environment:
      VIRTUAL_HOST: 'www.groupapp.io, groupapp.io'
      NODE_ENV: 'development'
      PORT: 80

version: '2'
